export const shortcuts = [
    { category: "General", action: "Open File", keys: ["Ctrl", "O"] },
    { category: "General", action: "Save File", keys: ["Ctrl", "S"] },
    { category: "General", action: "Undo", keys: ["Ctrl", "Z"] },
    { category: "General", action: "Redo", keys: ["Ctrl", "Shift", "Z"] },
    { category: "General", action: "Cancel", keys: ["Escape", "OR", "Right Mouse"] },
    { category: "General", action: "Search Menu", keys: ["F3"] },

    { category: "Navigation (3D View, ...)", action: "Orbit View", keys: ["Middle Mouse"], mouseAction: "DRAG"},
    { category: "Navigation (3D View, ...)", action: "Pan View", keys: ["Shift", "Middle Mouse"], mouseAction: "DRAG" },
    { category: "Navigation (3D View, ...)", action: "Zoom View (continuous)", keys: ["Ctrl", "Middle Mouse"], mouseAction: "DRAG" },
    { category: "Navigation (3D View, ...)", action: "Zoom View (stepwise)", keys: ["Middle Mouse"], mouseAction: "SCROLL WHEEL" },
    { category: "Navigation (3D View, ...)", action: "Focus Selected", keys: [". (Numpad)"] },

    { category: "Views (3D View only)", action: "Perspective/ortographic view (toggle)", keys: ["Numpad 5", "OR", "ICON"], icon: "Icons/blender_icon_view_perspective.svg" },
    { category: "Views (3D View only)", action: "Camera view (toggle)", keys: ["Numpad 0", "OR", "ICON"], icon: "Icons/blender_icon_view_camera.svg" },
    { category: "Views (3D View only)", action: "X-Ray view (toggle)", keys: ["Alt", "Z", "OR", "ICON_GROUP"], icons: ["Icons/blender_icon_xray.svg"] },
    { category: "Views (3D View only)", action: "Wireframe shading", keys: ["Z", "->", "4", "OR", "ICON_GROUP"], 
        icons: ["Icons/blender_icon_shading_wire.svg", 
        "Icons/blender_icon_shading_solid.svg", 
        "Icons/blender_icon_shading_texture.svg", 
        "Icons/blender_icon_shading_rendered.svg"],
        selected: 0,
    },
    { category: "Views (3D View only)", action: "Solid shading", keys: ["Z", "->", "6",  "OR", "ICON_GROUP"], 
        icons: ["Icons/blender_icon_shading_wire.svg", 
        "Icons/blender_icon_shading_solid.svg", 
        "Icons/blender_icon_shading_texture.svg", 
        "Icons/blender_icon_shading_rendered.svg"],
        selected: 1,
    },
    { category: "Views (3D View only)", action: "Material preview shading", keys: ["Z", "->", "2",  "OR", "ICON_GROUP"], 
        icons: ["Icons/blender_icon_shading_wire.svg", 
        "Icons/blender_icon_shading_solid.svg", 
        "Icons/blender_icon_shading_texture.svg", 
        "Icons/blender_icon_shading_rendered.svg"],
        selected: 2,
    },
    { category: "Views (3D View only)", action: "Rendered shading", keys: ["Z", "->", "8", "OR", "ICON_GROUP"], 
        icons: ["Icons/blender_icon_shading_wire.svg", 
        "Icons/blender_icon_shading_solid.svg", 
        "Icons/blender_icon_shading_texture.svg", 
        "Icons/blender_icon_shading_rendered.svg"],
        selected: 3,
    },

    { category: "Windows and panels (3D view, ...)", action: "Show/hide tool shelf", keys: ["T"] },
    { category: "Windows and panels (3D view, ...)", action: "Show/hide sidebar", keys: ["N"] },

    { category: "Object actions", action: "Rename active object", keys: ["F2"] },
    { category: "Object actions", action: "Translate (\"Grab\")", keys: ["G"] },
    { category: "Object actions", action: "Rotate", keys: ["R"] },
    { category: "Object actions", action: "Scale", keys: ["S"] },
    { category: "Object actions", action: "Reset transform i.e.:", keys: ["Alt", "G"] },
    { category: "Object actions", action: "Transf. along axis i.e.:", keys: ["G", "->", "X"] },
    { category: "Object actions", action: "Transf. along local axis i.e.:", keys: ["G", "->", "X", "->", "X"] },
    { category: "Object actions", action: "Transf. along plane i.e.:", keys: ["G", "->", "Shift", "X"] },
    { category: "Object actions", action: "Delete object(s)", keys: ["X", "OR", "Delete"] },
    { category: "Object actions", action: "Duplicate object(s)", keys: ["Shift", "D"] },
    { category: "Object actions", action: "Add object", keys: ["Shift", "A"] },
    { category: "Object actions", action: "Parent selectd object to active", keys: ["Ctrl", "P"] },
    { category: "Object actions", action: "Clear parent of selected object(s)", keys: ["Alt", "P"] },
    { category: "Object actions", action: "Join selected objects to active", keys: ["Ctrl", "J"] },
    { category: "Object actions", action: "Apply transforms", keys: ["Ctrl", "A"] },
    { category: "Object actions", action: "Subtract selection from active (booltools)", keys: ["Ctrl", "-"] },

    { category: "Edit Mode", action: "Toggle edit mode", keys: ["Tab ↹"] },
    { category: "Edit Mode", action: "Vertx|edge|face", keys: ["1", "|", "2", "|", "3", "OR", "ICON_GROUP"],
        icons: ["Icons/blender_icon_vertexsel.svg", 
        "Icons/blender_icon_edgesel.svg", 
        "Icons/blender_icon_facesel.svg",],
    },
    { category: "Edit Mode", action: "Extrude", keys: ["E"] },
    { category: "Edit Mode", action: "Alternative extrude", keys: ["Alt", "E"] },
    { category: "Edit Mode", action: "Inset faces", keys: ["I", "->", "I (inset individual)"] },
    { category: "Edit Mode", action: "Bevel", keys: ["Ctrl", "B", "->", "C (clamp overlap)"] },
    { category: "Edit Mode", action: "Loop Cut", keys: ["Ctrl", "R"] },
    { category: "Edit Mode", action: "Knife Tool", keys: ["K", "->", "C (cut through)", "OR", "A (angled)"] },
    { category: "Edit Mode", action: "Fill", keys: ["F"] },
    { category: "Edit Mode", action: "Recalculate outside", keys: ["Shift", "N"] },
    { category: "Edit Mode", action: "Merge by distance", keys: ["M", "->", "By Distance"] },
    { category: "Edit Mode", action: "Select linked", keys: ["Ctrl", "L"] },

    { category: "Selections", action: "Select single object/item", keys: ["Left Mouse"] },
    { category: "Selections", action: "Add object to selection", keys: ["Shift", "Left Mouse"] },
    { category: "Selections", action: "Box select", keys: ["B", "OR", "Left Mouse"], mouseAction: "DRAG" },
    { category: "Selections", action: "Select all", keys: ["A"] },
    { category: "Selections", action: "Deselect all", keys: ["Alt", "A"] },
    { category: "Selections", action: "Invert selection", keys: ["Ctrl", "I"] },

];